name: Stable release
on:
  push:
    branches: [main, test/ci]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install node dependencies
        run: npm install -g rollup && npm install -g typescript

      - name: Transpile typescript
        run: tsc

      - name: Show directories
        run: ls -lha scripts

      - name: Minify the js ha
        run: rollup ./scripts/start.js --file ./out/start.js --format iife

      - name: Minify the css
        run: ./bin/lit -f styles.env

      - name: Remove innecesary files and directories
        run: rm -rf .gitignore styles/src src bin environment.js styles.env tsconfig.json .github

      - name: Create directories
        run: mkdir -p styles/src temp/src/

      - name: Move javascript
        run: mv out/start.js scripts/start.js

      - name: Move css
        run: mv styles/out/master.css styles/src/master.css

      - name: Check the output
        run: ls -lha .

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: . # The folder the action should deploy.

      - name: get url # then we get the url of the github pages site
        env:
          GH_TOKEN: ${{ github.token }}
        run:
          | # we use the gh cli to get the url and save it in an environment variable
          url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          echo "url=$url" >> $GITHUB_ENV

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-description: |
            New version of ${{ github.event.repository.name }} docs was deployed 🚀

            ${{ env.url }}
